rotation:
    logLimit: 2097152 # 2MB
    keepFiles: 7
severity: Info
node:
    severity: Debug
    files: [node.log, node.log.pub]
    handlers:
      - file: node.pub
        round: 5
      - file: node
    comm:
        severity: Info
    dht:
        severity: Info
