rotation:
    logLimit: 2097152 # 2MB
    keepFiles: 20
severity: Debug
file: logs/explorer-node.log
node:
    plugin:
        notifier:
            severity: Debug
            file: logs/explorer.log
            socket-io:
                severity: Debug
                file: logs/socket-io.log

