rotation:
    logLimit: 2097152 # 2MB
    keepFiles: 20
severity: Error  # display only "node"'s log
file: explorer-node.log
node:
    severity: Debug
    plugin:
        notifier:
            severity: Debug
            file: explorer.log
            socket-io:
                severity: Debug
                file: socket-io.log

