flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

packages:
- '.'
- core
- update
- infra
- db
- lrc
- lwallet
- ssc
- godtossing
- tools
- txp

- location:
    # https://github.com/bos/wreq/pull/103
    git: https://github.com/JoeShanahanT/wreq.git
    commit: 9778f0d00ad9692d10008183ba9e8aa789e65674
  extra-dep: true
- location:
    git: https://github.com/fpco/store.git
    commit: 4b667d3b0a9cfa408ed0975e85ad279db543e9c5
  extra-dep: true
- location:
    git: https://github.com/tibbe/ekg-core
    commit: 4baee2a144d931d9e455988cff18bec9f2fa18d0
  extra-dep: true
- location:
    git: https://github.com/haskell/deepseq.git
    commit: 0b22c9825ef79c1ee41d2f19e7c997f5cdc93494
  extra-dep: true
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true
- location:
    git: https://github.com/domenkozar/acid-state.git
    commit: 750f603366067dc52a90d3dc21ba25b56f0f70c4
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: bbdca50c263c6dae251e67eb36a7d4e1ba7c1cb6
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: e2e2711e6978002279b4d7c49cab1aff47a2fd43
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: b4fbd07c077b41c0e948bd377f1662b599f0bc4c
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp-nt.git
    commit: 8bfba580e628791a03b0bec4d913890dde16811d # master
  extra-dep: true
# These two are needed for time-warp-nt
- location:
    git: https://github.com/serokell/network-transport-tcp
    commit: a6c04c35f3a1d786bc5e57fd04cf3e2a043179f3
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport
    commit: 0b8f5a7bec389a4ffa653792cfd203c742a0857b
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 1cde8e3a8d9093bbf571085920045c05edb3eaa4
  extra-dep: true
#- location:
#    git: https://github.com/haskell-crypto/cryptonite.git
#    commit: 2932df9e243aa7ae7eb2b25d7c60fa77a30c6fb5
#  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- universum-0.4.3
- time-units-1.0.0
- serokell-util-0.1.5.0
- pvss-0.1
- base58-bytestring-0.1.0
- log-warper-1.1.2
- concurrent-extra-0.7.0.10       # not yet in lts-8
# - purescript-bridge-0.8.0.1
- cryptonite-0.23
- cryptonite-openssl-0.6
- directory-1.3.1.0               # https://github.com/malcolmwallace/cpphs/issues/8
- servant-0.10                    # servant-multipart supports version servant-10 only
- servant-server-0.10             # so it triggers another dependencies to be v10
- servant-swagger-1.1.2.1
- servant-multipart-0.10
- ether-0.5.1.0
- transformers-lift-0.2.0.1
- lens-4.15.3                     # not yet in lts-8
- th-abstraction-0.2.2.0          # needed for lens
- rocksdb-haskell-1.0.0
- generic-arbitrary-0.1.0
- happy-1.19.5                    # https://github.com/commercialhaskell/stack/issues/3151
- entropy-0.3.7                   # https://github.com/commercialhaskell/stack/issues/3151
- swagger2-2.1.4.1

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

# If you find it too restrictive, you can use `scripts/build/cardano-sl.sh' script
ghc-options:
  cardano-sl-core:       -Werror
  cardano-sl-db:         -Werror
  cardano-sl-ssc:        -Werror
  cardano-sl-infra:      -Werror
  cardano-sl-lrc:        -Werror
  cardano-sl-update:     -Werror
  cardano-sl-godtossing: -Werror
  cardano-sl-txp:        -Werror
  cardano-sl:            -Werror
  cardano-sl-tools:      -Werror
  cardano-sl-lwallet:    -Werror

compiler: ghc-8.2.0.20170704
compiler-check: match-exact
resolver: nightly-2017-07-19
allow-newer: true

setup-info:
  ghc:
    linux64:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-deb8-linux.tar.xz
        content-length: 138482820
        sha1: ac1598c21ea2936b091885a29a0f5725668aaed5

    macosx:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-apple-darwin.tar.xz
        content-length: 125197252
        sha1: 81e3093b559b9aaf8af2a89f182539849539cbe1

    windows64:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-unknown-mingw32.tar.xz
        content-length: 175463160
        sha1: 3648302c66769d4aa0c3a9f82be4538f402f234f
