resolver: lts-7.16
compiler: ghc-8.0.2

packages:
  - '.'
  - location:
      git: https://github.com/serokell/kademlia.git
      commit: 278171b8ab104c78aa95bcdd9b63c8ced4fb1ed2
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport-tcp
      commit: 705b3c0d44cb1f4eea904b54431cd467e62dda35
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport
      commit: e7a5f44d0d98370d16df103c9dc61ef7bf15aee8
    extra-dep: true

extra-deps:
  - network-transport-inmemory-0.5.2

nix:
  enable: false
  packages: []

extra-deps:
  - serokell-util-0.1.3.2
  - time-units-1.0.0
  - pqueue-1.3.2
  - aeson-extra-0.4.0.0
  - data-msgpack-0.0.8
  - recursion-schemes-5.0.1
  - log-warper-0.4.1
  - universum-0.2.1

flags: {}
extra-package-dbs: []
