flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: 500a168f4cffb7b11d8fdcae30e837e937bf83e4
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp.git
    commit: b7cb94742df6a7d035294592fde1b59f27397fc8
  extra-dep: true
- location:
    git: https://github.com/serokell/serokell-core.git
    commit: 8f95bdb1f9f30a9e90edaf95794c75d9e7fa7d1b
  extra-dep: true
- location:
    git: https://github.com/TokTok/hs-msgpack.git
    commit: d4abb4a320250047f512f2b3860fa051f9b530ac
  extra-dep: true
- location:
    git: https://github.com/serokell/msgpack-haskell.git
    commit: 1bef097a0458768997ddb0a40793463f443c6a7e
  extra-dep: true
  subdirs:
    - msgpack-rpc
- location:
    git: https://github.com/serokell/acid-state.git
    commit: dea606c78d9ecd22247e3c90dcf12c6b4b0458fc
  extra-dep: true
- location:
    git: git@github.com:input-output-hk/pvss-haskell.git
    commit: 996951c97f97d734ec7cea05e72620eaabfc72f3
  extra-dep: true

extra-deps:
- pqueue-1.3.2
- time-units-1.0.0
- aeson-extra-0.4.0.0
- recursion-schemes-5
- QuickCheck-2.9.2
- cryptonite-openssl-0.2
- kademlia-1.1.0.0

resolver: lts-7.1
