resolver: lts-7.13

packages:
  - '.'
  - location:
      git: https://github.com/serokell/kademlia.git
      commit: 7a0bdfe8bba2503ab96bddd9021ba36e50e5ccc2
    extra-dep: true

extra-deps:
  - network-transport-inmemory-0.5.2

nix:
  enable: false
  packages: []


flags: {}
extra-package-dbs: []
