flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: 8e33495fd58c5443e0c2b0f1b6646516a47bd8d6
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp.git
    commit: 7b3d9bd4a9ad5df5feee8b124805df0144304a50
  extra-dep: true
- location:
    git: https://github.com/serokell/serokell-util.git
    commit: 3fd9a911211276f1f2a2a9fe78bddbb2e1ffd503
  extra-dep: true
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 405e41b671d3ffb17a837b45e7d01a2b635c1061
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/pvss-haskell.git
    commit: 1b898a222341116d210f2d3a5566028e14a335ae
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: fd18875c31e0f351733099bd632d5898dcf5840d
  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- pqueue-1.3.2
- data-msgpack-0.0.8
- time-units-1.0.0
- aeson-extra-0.4.0.0
- recursion-schemes-5
- QuickCheck-2.9.2
- cryptonite-openssl-0.2
- UtilityTM-0.0.4

resolver: lts-7.1
