flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: 500a168f4cffb7b11d8fdcae30e837e937bf83e4
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp.git
    commit: 9182b1991eef03fd59f02b6f220abb48d079009b
  extra-dep: true
- location:
    git: https://github.com/serokell/serokell-core.git
    commit: 418841fab8ca0b300868943260bcaa9e5f3fcf16
  extra-dep: true
- location:
    git: https://github.com/serokell/msgpack-haskell.git
    commit: 20691fa4f85ef2a75c5808a5b2e69fd28fdaa159
  extra-dep: true
  subdirs:
    - msgpack
    - msgpack-rpc

extra-deps:
- binary-0.7.6.1
- pqueue-1.3.2
- time-units-1.0.0
- aeson-extra-0.4.0.0
- recursion-schemes-5
- QuickCheck-2.9.2

resolver: lts-7.1
