flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: 113a99252d2684a6d4e9db6359790debb48eadbb
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp.git
    commit: c37a6450b87253e40e57aedb2829f05d172d34ab
  extra-dep: true
- location:
    git: https://github.com/serokell/serokell-core.git
    commit: bed778711b7912cc2f2189e092c50363a9c133e3
  extra-dep: true

extra-deps:
- binary-0.7.6.1
- msgpack-1.0.0
- msgpack-rpc-1.0.0
- pqueue-1.3.2
- time-units-1.0.0
- aeson-extra-0.4.0.0
- recursion-schemes-5

resolver: lts-7.1
