flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/serokell/protolude
    commit: 1cb06305292cb01719251891365496de2c20b850
  extra-dep: true

resolver: lts-6.15
