flags: {}

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: 113a99252d2684a6d4e9db6359790debb48eadbb
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp.git
    commit: c37a6450b87253e40e57aedb2829f05d172d34ab
  extra-dep: true
- location:
    git: https://github.com/serokell/serokell-core.git
    commit: a2711a163577165c6a15895239d88c6a53dd6bd2
  extra-dep: true

extra-deps:
- binary-0.7.6.1
- msgpack-1.0.0
- msgpack-rpc-1.0.0
- pqueue-1.3.2
- time-units-1.0.0
- aeson-extra-0.4.0.0
- recursion-schemes-5
- QuickCheck-2.9.2

resolver: lts-7.1
