resolver: lts-8.2

packages:
  - '.'
  - location:
      git: https://github.com/serokell/kademlia.git
      commit: 278171b8ab104c78aa95bcdd9b63c8ced4fb1ed2
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport-tcp
      commit: 8fb61171a0f09e554c051ca112e3967cea6b7f69
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport
      commit: f2321a103f53f51d36c99383132e3ffa3ef1c401
    extra-dep: true
  - location:
      git: https://github.com/avieth/network-transport-inmemory
      commit: c6893b17531ed47838c8d8f0bf434cf0119b50df
    extra-dep: true

nix:
  enable: false
  packages: []

extra-deps:
  - serokell-util-0.1.3.5
  - time-units-1.0.0
  - log-warper-0.4.4
  - universum-0.2.1

flags: {}
extra-package-dbs: []
