rotation:
    logLimit: 10485760 # 10MB
    keepFiles: 20
severity: Debug
node:
    severity: Debug
    handlers:
      - file: node.pub
        round: 1
      - file: node
    comm:
        severity: Debug
    dht:
        severity: Info
    worker:
      us:
        severity: Debug
